// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: allocator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RunnerAllocatorService_RequestSlot_FullMethodName = "/allocator.RunnerAllocatorService/RequestSlot"
	RunnerAllocatorService_ReleaseSlot_FullMethodName = "/allocator.RunnerAllocatorService/ReleaseSlot"
	RunnerAllocatorService_GetStatus_FullMethodName   = "/allocator.RunnerAllocatorService/GetStatus"
)

// RunnerAllocatorServiceClient is the client API for RunnerAllocatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Runner-Allocator Service
// Manages 3 fixed runner containers + queue system
type RunnerAllocatorServiceClient interface {
	// Request a workspace slot for a user
	RequestSlot(ctx context.Context, in *SlotRequest, opts ...grpc.CallOption) (*SlotResponse, error)
	// Release a workspace slot
	ReleaseSlot(ctx context.Context, in *ReleaseSlotRequest, opts ...grpc.CallOption) (*ReleaseSlotResponse, error)
	// Get current allocation status
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type runnerAllocatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnerAllocatorServiceClient(cc grpc.ClientConnInterface) RunnerAllocatorServiceClient {
	return &runnerAllocatorServiceClient{cc}
}

func (c *runnerAllocatorServiceClient) RequestSlot(ctx context.Context, in *SlotRequest, opts ...grpc.CallOption) (*SlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SlotResponse)
	err := c.cc.Invoke(ctx, RunnerAllocatorService_RequestSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerAllocatorServiceClient) ReleaseSlot(ctx context.Context, in *ReleaseSlotRequest, opts ...grpc.CallOption) (*ReleaseSlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseSlotResponse)
	err := c.cc.Invoke(ctx, RunnerAllocatorService_ReleaseSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerAllocatorServiceClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, RunnerAllocatorService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunnerAllocatorServiceServer is the server API for RunnerAllocatorService service.
// All implementations must embed UnimplementedRunnerAllocatorServiceServer
// for forward compatibility.
//
// Runner-Allocator Service
// Manages 3 fixed runner containers + queue system
type RunnerAllocatorServiceServer interface {
	// Request a workspace slot for a user
	RequestSlot(context.Context, *SlotRequest) (*SlotResponse, error)
	// Release a workspace slot
	ReleaseSlot(context.Context, *ReleaseSlotRequest) (*ReleaseSlotResponse, error)
	// Get current allocation status
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedRunnerAllocatorServiceServer()
}

// UnimplementedRunnerAllocatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunnerAllocatorServiceServer struct{}

func (UnimplementedRunnerAllocatorServiceServer) RequestSlot(context.Context, *SlotRequest) (*SlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestSlot not implemented")
}
func (UnimplementedRunnerAllocatorServiceServer) ReleaseSlot(context.Context, *ReleaseSlotRequest) (*ReleaseSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseSlot not implemented")
}
func (UnimplementedRunnerAllocatorServiceServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedRunnerAllocatorServiceServer) mustEmbedUnimplementedRunnerAllocatorServiceServer() {
}
func (UnimplementedRunnerAllocatorServiceServer) testEmbeddedByValue() {}

// UnsafeRunnerAllocatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnerAllocatorServiceServer will
// result in compilation errors.
type UnsafeRunnerAllocatorServiceServer interface {
	mustEmbedUnimplementedRunnerAllocatorServiceServer()
}

func RegisterRunnerAllocatorServiceServer(s grpc.ServiceRegistrar, srv RunnerAllocatorServiceServer) {
	// If the following call pancis, it indicates UnimplementedRunnerAllocatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RunnerAllocatorService_ServiceDesc, srv)
}

func _RunnerAllocatorService_RequestSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerAllocatorServiceServer).RequestSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerAllocatorService_RequestSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerAllocatorServiceServer).RequestSlot(ctx, req.(*SlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerAllocatorService_ReleaseSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerAllocatorServiceServer).ReleaseSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerAllocatorService_ReleaseSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerAllocatorServiceServer).ReleaseSlot(ctx, req.(*ReleaseSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerAllocatorService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerAllocatorServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerAllocatorService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerAllocatorServiceServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RunnerAllocatorService_ServiceDesc is the grpc.ServiceDesc for RunnerAllocatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunnerAllocatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "allocator.RunnerAllocatorService",
	HandlerType: (*RunnerAllocatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestSlot",
			Handler:    _RunnerAllocatorService_RequestSlot_Handler,
		},
		{
			MethodName: "ReleaseSlot",
			Handler:    _RunnerAllocatorService_ReleaseSlot_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _RunnerAllocatorService_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "allocator.proto",
}
