// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: allocator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	TemplateType  string                 `protobuf:"bytes,3,opt,name=template_type,json=templateType,proto3" json:"template_type,omitempty"` // "react-vite" | "nodejs-express" | "blank"
	GithubRepo    string                 `protobuf:"bytes,4,opt,name=github_repo,json=githubRepo,proto3" json:"github_repo,omitempty"`       // optional: clone from GitHub
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotRequest) Reset() {
	*x = SlotRequest{}
	mi := &file_allocator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotRequest) ProtoMessage() {}

func (x *SlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_allocator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotRequest.ProtoReflect.Descriptor instead.
func (*SlotRequest) Descriptor() ([]byte, []int) {
	return file_allocator_proto_rawDescGZIP(), []int{0}
}

func (x *SlotRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SlotRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SlotRequest) GetTemplateType() string {
	if x != nil {
		return x.TemplateType
	}
	return ""
}

func (x *SlotRequest) GetGithubRepo() string {
	if x != nil {
		return x.GithubRepo
	}
	return ""
}

type SlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PodIp         string                 `protobuf:"bytes,2,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	PreviewPort   int32                  `protobuf:"varint,3,opt,name=preview_port,json=previewPort,proto3" json:"preview_port,omitempty"`    // port 3000 for user app
	TerminalPort  int32                  `protobuf:"varint,4,opt,name=terminal_port,json=terminalPort,proto3" json:"terminal_port,omitempty"` // port 7681 for ttyd terminal
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                                  // "allocated" | "queued" | "error"
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotResponse) Reset() {
	*x = SlotResponse{}
	mi := &file_allocator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotResponse) ProtoMessage() {}

func (x *SlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_allocator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotResponse.ProtoReflect.Descriptor instead.
func (*SlotResponse) Descriptor() ([]byte, []int) {
	return file_allocator_proto_rawDescGZIP(), []int{1}
}

func (x *SlotResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SlotResponse) GetPodIp() string {
	if x != nil {
		return x.PodIp
	}
	return ""
}

func (x *SlotResponse) GetPreviewPort() int32 {
	if x != nil {
		return x.PreviewPort
	}
	return 0
}

func (x *SlotResponse) GetTerminalPort() int32 {
	if x != nil {
		return x.TerminalPort
	}
	return 0
}

func (x *SlotResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SlotResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReleaseSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSlotRequest) Reset() {
	*x = ReleaseSlotRequest{}
	mi := &file_allocator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSlotRequest) ProtoMessage() {}

func (x *ReleaseSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_allocator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSlotRequest.ProtoReflect.Descriptor instead.
func (*ReleaseSlotRequest) Descriptor() ([]byte, []int) {
	return file_allocator_proto_rawDescGZIP(), []int{2}
}

func (x *ReleaseSlotRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReleaseSlotRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ReleaseSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSlotResponse) Reset() {
	*x = ReleaseSlotResponse{}
	mi := &file_allocator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSlotResponse) ProtoMessage() {}

func (x *ReleaseSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_allocator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSlotResponse.ProtoReflect.Descriptor instead.
func (*ReleaseSlotResponse) Descriptor() ([]byte, []int) {
	return file_allocator_proto_rawDescGZIP(), []int{3}
}

func (x *ReleaseSlotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReleaseSlotResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_allocator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_allocator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_allocator_proto_rawDescGZIP(), []int{4}
}

type StatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActiveSlots    int32                  `protobuf:"varint,1,opt,name=active_slots,json=activeSlots,proto3" json:"active_slots,omitempty"`
	QueuedUsers    int32                  `protobuf:"varint,2,opt,name=queued_users,json=queuedUsers,proto3" json:"queued_users,omitempty"`
	AvailableSlots int32                  `protobuf:"varint,3,opt,name=available_slots,json=availableSlots,proto3" json:"available_slots,omitempty"`
	Slots          []*RunnerSlot          `protobuf:"bytes,4,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_allocator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_allocator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_allocator_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetActiveSlots() int32 {
	if x != nil {
		return x.ActiveSlots
	}
	return 0
}

func (x *StatusResponse) GetQueuedUsers() int32 {
	if x != nil {
		return x.QueuedUsers
	}
	return 0
}

func (x *StatusResponse) GetAvailableSlots() int32 {
	if x != nil {
		return x.AvailableSlots
	}
	return 0
}

func (x *StatusResponse) GetSlots() []*RunnerSlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

type RunnerSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // "idle" | "active" | "building"
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerSlot) Reset() {
	*x = RunnerSlot{}
	mi := &file_allocator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerSlot) ProtoMessage() {}

func (x *RunnerSlot) ProtoReflect() protoreflect.Message {
	mi := &file_allocator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerSlot.ProtoReflect.Descriptor instead.
func (*RunnerSlot) Descriptor() ([]byte, []int) {
	return file_allocator_proto_rawDescGZIP(), []int{6}
}

func (x *RunnerSlot) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *RunnerSlot) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RunnerSlot) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *RunnerSlot) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RunnerSlot) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RunnerSlot) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_allocator_proto protoreflect.FileDescriptor

const file_allocator_proto_rawDesc = "" +
	"\n" +
	"\x0fallocator.proto\x12\tallocator\"\x8b\x01\n" +
	"\vSlotRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12#\n" +
	"\rtemplate_type\x18\x03 \x01(\tR\ftemplateType\x12\x1f\n" +
	"\vgithub_repo\x18\x04 \x01(\tR\n" +
	"githubRepo\"\xbe\x01\n" +
	"\fSlotResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06pod_ip\x18\x02 \x01(\tR\x05podIp\x12!\n" +
	"\fpreview_port\x18\x03 \x01(\x05R\vpreviewPort\x12#\n" +
	"\rterminal_port\x18\x04 \x01(\x05R\fterminalPort\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"L\n" +
	"\x12ReleaseSlotRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"I\n" +
	"\x13ReleaseSlotResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0f\n" +
	"\rStatusRequest\"\xac\x01\n" +
	"\x0eStatusResponse\x12!\n" +
	"\factive_slots\x18\x01 \x01(\x05R\vactiveSlots\x12!\n" +
	"\fqueued_users\x18\x02 \x01(\x05R\vqueuedUsers\x12'\n" +
	"\x0favailable_slots\x18\x03 \x01(\x05R\x0eavailableSlots\x12+\n" +
	"\x05slots\x18\x04 \x03(\v2\x15.allocator.RunnerSlotR\x05slots\"\xb3\x01\n" +
	"\n" +
	"RunnerSlot\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt2\xe8\x01\n" +
	"\x16RunnerAllocatorService\x12>\n" +
	"\vRequestSlot\x12\x16.allocator.SlotRequest\x1a\x17.allocator.SlotResponse\x12L\n" +
	"\vReleaseSlot\x12\x1d.allocator.ReleaseSlotRequest\x1a\x1e.allocator.ReleaseSlotResponse\x12@\n" +
	"\tGetStatus\x12\x18.allocator.StatusRequest\x1a\x19.allocator.StatusResponseB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_allocator_proto_rawDescOnce sync.Once
	file_allocator_proto_rawDescData []byte
)

func file_allocator_proto_rawDescGZIP() []byte {
	file_allocator_proto_rawDescOnce.Do(func() {
		file_allocator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_allocator_proto_rawDesc), len(file_allocator_proto_rawDesc)))
	})
	return file_allocator_proto_rawDescData
}

var file_allocator_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_allocator_proto_goTypes = []any{
	(*SlotRequest)(nil),         // 0: allocator.SlotRequest
	(*SlotResponse)(nil),        // 1: allocator.SlotResponse
	(*ReleaseSlotRequest)(nil),  // 2: allocator.ReleaseSlotRequest
	(*ReleaseSlotResponse)(nil), // 3: allocator.ReleaseSlotResponse
	(*StatusRequest)(nil),       // 4: allocator.StatusRequest
	(*StatusResponse)(nil),      // 5: allocator.StatusResponse
	(*RunnerSlot)(nil),          // 6: allocator.RunnerSlot
}
var file_allocator_proto_depIdxs = []int32{
	6, // 0: allocator.StatusResponse.slots:type_name -> allocator.RunnerSlot
	0, // 1: allocator.RunnerAllocatorService.RequestSlot:input_type -> allocator.SlotRequest
	2, // 2: allocator.RunnerAllocatorService.ReleaseSlot:input_type -> allocator.ReleaseSlotRequest
	4, // 3: allocator.RunnerAllocatorService.GetStatus:input_type -> allocator.StatusRequest
	1, // 4: allocator.RunnerAllocatorService.RequestSlot:output_type -> allocator.SlotResponse
	3, // 5: allocator.RunnerAllocatorService.ReleaseSlot:output_type -> allocator.ReleaseSlotResponse
	5, // 6: allocator.RunnerAllocatorService.GetStatus:output_type -> allocator.StatusResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_allocator_proto_init() }
func file_allocator_proto_init() {
	if File_allocator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_allocator_proto_rawDesc), len(file_allocator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_allocator_proto_goTypes,
		DependencyIndexes: file_allocator_proto_depIdxs,
		MessageInfos:      file_allocator_proto_msgTypes,
	}.Build()
	File_allocator_proto = out.File
	file_allocator_proto_goTypes = nil
	file_allocator_proto_depIdxs = nil
}
