// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/auth_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupRequest) Reset() {
	*x = SignupRequest{}
	mi := &file_proto_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupRequest) ProtoMessage() {}

func (x *SignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupRequest.ProtoReflect.Descriptor instead.
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *SignupRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignupRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_service_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_proto_auth_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_service_proto_rawDescGZIP(), []int{2}
}

func (x *AuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetGoogleAuthURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoogleAuthURLRequest) Reset() {
	*x = GetGoogleAuthURLRequest{}
	mi := &file_proto_auth_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoogleAuthURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoogleAuthURLRequest) ProtoMessage() {}

func (x *GetGoogleAuthURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoogleAuthURLRequest.ProtoReflect.Descriptor instead.
func (*GetGoogleAuthURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetGoogleAuthURLRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type GetGoogleAuthURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoogleAuthURLResponse) Reset() {
	*x = GetGoogleAuthURLResponse{}
	mi := &file_proto_auth_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoogleAuthURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoogleAuthURLResponse) ProtoMessage() {}

func (x *GetGoogleAuthURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoogleAuthURLResponse.ProtoReflect.Descriptor instead.
func (*GetGoogleAuthURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetGoogleAuthURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type HandleGoogleCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleGoogleCallbackRequest) Reset() {
	*x = HandleGoogleCallbackRequest{}
	mi := &file_proto_auth_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleGoogleCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleGoogleCallbackRequest) ProtoMessage() {}

func (x *HandleGoogleCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleGoogleCallbackRequest.ProtoReflect.Descriptor instead.
func (*HandleGoogleCallbackRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_service_proto_rawDescGZIP(), []int{5}
}

func (x *HandleGoogleCallbackRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetGitHubAuthURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGitHubAuthURLRequest) Reset() {
	*x = GetGitHubAuthURLRequest{}
	mi := &file_proto_auth_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGitHubAuthURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGitHubAuthURLRequest) ProtoMessage() {}

func (x *GetGitHubAuthURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGitHubAuthURLRequest.ProtoReflect.Descriptor instead.
func (*GetGitHubAuthURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_service_proto_rawDescGZIP(), []int{6}
}

type GetGitHubAuthURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGitHubAuthURLResponse) Reset() {
	*x = GetGitHubAuthURLResponse{}
	mi := &file_proto_auth_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGitHubAuthURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGitHubAuthURLResponse) ProtoMessage() {}

func (x *GetGitHubAuthURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGitHubAuthURLResponse.ProtoReflect.Descriptor instead.
func (*GetGitHubAuthURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetGitHubAuthURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type HandleGitHubCallbackRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InstallationId int64                  `protobuf:"varint,2,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HandleGitHubCallbackRequest) Reset() {
	*x = HandleGitHubCallbackRequest{}
	mi := &file_proto_auth_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleGitHubCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleGitHubCallbackRequest) ProtoMessage() {}

func (x *HandleGitHubCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleGitHubCallbackRequest.ProtoReflect.Descriptor instead.
func (*HandleGitHubCallbackRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_service_proto_rawDescGZIP(), []int{8}
}

func (x *HandleGitHubCallbackRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HandleGitHubCallbackRequest) GetInstallationId() int64 {
	if x != nil {
		return x.InstallationId
	}
	return 0
}

type GetGitHubAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGitHubAccessTokenRequest) Reset() {
	*x = GetGitHubAccessTokenRequest{}
	mi := &file_proto_auth_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGitHubAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGitHubAccessTokenRequest) ProtoMessage() {}

func (x *GetGitHubAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGitHubAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*GetGitHubAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetGitHubAccessTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetGitHubAccessTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGitHubAccessTokenResponse) Reset() {
	*x = GetGitHubAccessTokenResponse{}
	mi := &file_proto_auth_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGitHubAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGitHubAccessTokenResponse) ProtoMessage() {}

func (x *GetGitHubAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGitHubAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*GetGitHubAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetGitHubAccessTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetGitHubAccessTokenResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GenerateRepoTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRepoTokenRequest) Reset() {
	*x = GenerateRepoTokenRequest{}
	mi := &file_proto_auth_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRepoTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRepoTokenRequest) ProtoMessage() {}

func (x *GenerateRepoTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRepoTokenRequest.ProtoReflect.Descriptor instead.
func (*GenerateRepoTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_service_proto_rawDescGZIP(), []int{11}
}

func (x *GenerateRepoTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GenerateRepoTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRepoTokenResponse) Reset() {
	*x = GenerateRepoTokenResponse{}
	mi := &file_proto_auth_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRepoTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRepoTokenResponse) ProtoMessage() {}

func (x *GenerateRepoTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRepoTokenResponse.ProtoReflect.Descriptor instead.
func (*GenerateRepoTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_service_proto_rawDescGZIP(), []int{12}
}

func (x *GenerateRepoTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GenerateRepoTokenResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_proto_auth_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_service_proto_rawDescGZIP(), []int{13}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_proto_auth_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_service_proto_rawDescGZIP(), []int{14}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateTokenResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_auth_service_proto protoreflect.FileDescriptor

const file_proto_auth_service_proto_rawDesc = "" +
	"\n" +
	"\x18proto/auth_service.proto\x12\x04auth\"A\n" +
	"\rSignupRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\":\n" +
	"\fAuthResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"/\n" +
	"\x17GetGoogleAuthURLRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\",\n" +
	"\x18GetGoogleAuthURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"1\n" +
	"\x1bHandleGoogleCallbackRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\x19\n" +
	"\x17GetGitHubAuthURLRequest\",\n" +
	"\x18GetGitHubAuthURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"_\n" +
	"\x1bHandleGitHubCallbackRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0finstallation_id\x18\x02 \x01(\x03R\x0einstallationId\"6\n" +
	"\x1bGetGitHubAccessTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"P\n" +
	"\x1cGetGitHubAccessTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"3\n" +
	"\x18GenerateRepoTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"M\n" +
	"\x19GenerateRepoTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\\\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xb4\x05\n" +
	"\vAuthService\x121\n" +
	"\x06Signup\x12\x13.auth.SignupRequest\x1a\x12.auth.AuthResponse\x12/\n" +
	"\x05Login\x12\x12.auth.LoginRequest\x1a\x12.auth.AuthResponse\x12M\n" +
	"\x14HandleGoogleCallback\x12!.auth.HandleGoogleCallbackRequest\x1a\x12.auth.AuthResponse\x12Q\n" +
	"\x10GetGoogleAuthURL\x12\x1d.auth.GetGoogleAuthURLRequest\x1a\x1e.auth.GetGoogleAuthURLResponse\x12Q\n" +
	"\x10GetGitHubAuthURL\x12\x1d.auth.GetGitHubAuthURLRequest\x1a\x1e.auth.GetGitHubAuthURLResponse\x12M\n" +
	"\x14HandleGitHubCallback\x12!.auth.HandleGitHubCallbackRequest\x1a\x12.auth.AuthResponse\x12]\n" +
	"\x14GetGitHubAccessToken\x12!.auth.GetGitHubAccessTokenRequest\x1a\".auth.GetGitHubAccessTokenResponse\x12T\n" +
	"\x11GenerateRepoToken\x12\x1e.auth.GenerateRepoTokenRequest\x1a\x1f.auth.GenerateRepoTokenResponse\x12H\n" +
	"\rValidateToken\x12\x1a.auth.ValidateTokenRequest\x1a\x1b.auth.ValidateTokenResponseB-Z+github.com/Aadithya-J/code_nest/proto;protob\x06proto3"

var (
	file_proto_auth_service_proto_rawDescOnce sync.Once
	file_proto_auth_service_proto_rawDescData []byte
)

func file_proto_auth_service_proto_rawDescGZIP() []byte {
	file_proto_auth_service_proto_rawDescOnce.Do(func() {
		file_proto_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_service_proto_rawDesc), len(file_proto_auth_service_proto_rawDesc)))
	})
	return file_proto_auth_service_proto_rawDescData
}

var file_proto_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_auth_service_proto_goTypes = []any{
	(*SignupRequest)(nil),                // 0: auth.SignupRequest
	(*LoginRequest)(nil),                 // 1: auth.LoginRequest
	(*AuthResponse)(nil),                 // 2: auth.AuthResponse
	(*GetGoogleAuthURLRequest)(nil),      // 3: auth.GetGoogleAuthURLRequest
	(*GetGoogleAuthURLResponse)(nil),     // 4: auth.GetGoogleAuthURLResponse
	(*HandleGoogleCallbackRequest)(nil),  // 5: auth.HandleGoogleCallbackRequest
	(*GetGitHubAuthURLRequest)(nil),      // 6: auth.GetGitHubAuthURLRequest
	(*GetGitHubAuthURLResponse)(nil),     // 7: auth.GetGitHubAuthURLResponse
	(*HandleGitHubCallbackRequest)(nil),  // 8: auth.HandleGitHubCallbackRequest
	(*GetGitHubAccessTokenRequest)(nil),  // 9: auth.GetGitHubAccessTokenRequest
	(*GetGitHubAccessTokenResponse)(nil), // 10: auth.GetGitHubAccessTokenResponse
	(*GenerateRepoTokenRequest)(nil),     // 11: auth.GenerateRepoTokenRequest
	(*GenerateRepoTokenResponse)(nil),    // 12: auth.GenerateRepoTokenResponse
	(*ValidateTokenRequest)(nil),         // 13: auth.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),        // 14: auth.ValidateTokenResponse
}
var file_proto_auth_service_proto_depIdxs = []int32{
	0,  // 0: auth.AuthService.Signup:input_type -> auth.SignupRequest
	1,  // 1: auth.AuthService.Login:input_type -> auth.LoginRequest
	5,  // 2: auth.AuthService.HandleGoogleCallback:input_type -> auth.HandleGoogleCallbackRequest
	3,  // 3: auth.AuthService.GetGoogleAuthURL:input_type -> auth.GetGoogleAuthURLRequest
	6,  // 4: auth.AuthService.GetGitHubAuthURL:input_type -> auth.GetGitHubAuthURLRequest
	8,  // 5: auth.AuthService.HandleGitHubCallback:input_type -> auth.HandleGitHubCallbackRequest
	9,  // 6: auth.AuthService.GetGitHubAccessToken:input_type -> auth.GetGitHubAccessTokenRequest
	11, // 7: auth.AuthService.GenerateRepoToken:input_type -> auth.GenerateRepoTokenRequest
	13, // 8: auth.AuthService.ValidateToken:input_type -> auth.ValidateTokenRequest
	2,  // 9: auth.AuthService.Signup:output_type -> auth.AuthResponse
	2,  // 10: auth.AuthService.Login:output_type -> auth.AuthResponse
	2,  // 11: auth.AuthService.HandleGoogleCallback:output_type -> auth.AuthResponse
	4,  // 12: auth.AuthService.GetGoogleAuthURL:output_type -> auth.GetGoogleAuthURLResponse
	7,  // 13: auth.AuthService.GetGitHubAuthURL:output_type -> auth.GetGitHubAuthURLResponse
	2,  // 14: auth.AuthService.HandleGitHubCallback:output_type -> auth.AuthResponse
	10, // 15: auth.AuthService.GetGitHubAccessToken:output_type -> auth.GetGitHubAccessTokenResponse
	12, // 16: auth.AuthService.GenerateRepoToken:output_type -> auth.GenerateRepoTokenResponse
	14, // 17: auth.AuthService.ValidateToken:output_type -> auth.ValidateTokenResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_auth_service_proto_init() }
func file_proto_auth_service_proto_init() {
	if File_proto_auth_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_service_proto_rawDesc), len(file_proto_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_service_proto_goTypes,
		DependencyIndexes: file_proto_auth_service_proto_depIdxs,
		MessageInfos:      file_proto_auth_service_proto_msgTypes,
	}.Build()
	File_proto_auth_service_proto = out.File
	file_proto_auth_service_proto_goTypes = nil
	file_proto_auth_service_proto_depIdxs = nil
}
