// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: auth.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_Signup_FullMethodName               = "/proto.AuthService/Signup"
	AuthService_Login_FullMethodName                = "/proto.AuthService/Login"
	AuthService_ValidateToken_FullMethodName        = "/proto.AuthService/ValidateToken"
	AuthService_GetGoogleAuthURL_FullMethodName     = "/proto.AuthService/GetGoogleAuthURL"
	AuthService_HandleGoogleCallback_FullMethodName = "/proto.AuthService/HandleGoogleCallback"
	AuthService_GetGitHubAuthURL_FullMethodName     = "/proto.AuthService/GetGitHubAuthURL"
	AuthService_HandleGitHubCallback_FullMethodName = "/proto.AuthService/HandleGitHubCallback"
	AuthService_GetGitHubAccessToken_FullMethodName = "/proto.AuthService/GetGitHubAccessToken"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthService defines gRPC methods for authentication
type AuthServiceClient interface {
	// Signup creates a new user account
	Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// Login authenticates a user and returns a JWT token
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// ValidateToken verifies a JWT and returns the user ID if valid
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
	// GetGoogleAuthURL retrieves the Google authentication URL
	GetGoogleAuthURL(ctx context.Context, in *GetGoogleAuthURLRequest, opts ...grpc.CallOption) (*GetGoogleAuthURLResponse, error)
	// HandleGoogleCallback handles the callback from Google authentication
	HandleGoogleCallback(ctx context.Context, in *HandleGoogleCallbackRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// GitHub OAuth flow – step 1: get install URL
	GetGitHubAuthURL(ctx context.Context, in *GetGitHubAuthURLRequest, opts ...grpc.CallOption) (*GetGitHubAuthURLResponse, error)
	// GitHub OAuth flow – step 2: handle callback with installation_id
	HandleGitHubCallback(ctx context.Context, in *HandleGitHubCallbackRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// Internal – runner-allocator asks for 1-hour access token
	GetGitHubAccessToken(ctx context.Context, in *GetGitHubAccessTokenRequest, opts ...grpc.CallOption) (*GetGitHubAccessTokenResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, AuthService_Signup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, AuthService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_ValidateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetGoogleAuthURL(ctx context.Context, in *GetGoogleAuthURLRequest, opts ...grpc.CallOption) (*GetGoogleAuthURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGoogleAuthURLResponse)
	err := c.cc.Invoke(ctx, AuthService_GetGoogleAuthURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) HandleGoogleCallback(ctx context.Context, in *HandleGoogleCallbackRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, AuthService_HandleGoogleCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetGitHubAuthURL(ctx context.Context, in *GetGitHubAuthURLRequest, opts ...grpc.CallOption) (*GetGitHubAuthURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGitHubAuthURLResponse)
	err := c.cc.Invoke(ctx, AuthService_GetGitHubAuthURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) HandleGitHubCallback(ctx context.Context, in *HandleGitHubCallbackRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, AuthService_HandleGitHubCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetGitHubAccessToken(ctx context.Context, in *GetGitHubAccessTokenRequest, opts ...grpc.CallOption) (*GetGitHubAccessTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGitHubAccessTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_GetGitHubAccessToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
//
// AuthService defines gRPC methods for authentication
type AuthServiceServer interface {
	// Signup creates a new user account
	Signup(context.Context, *SignupRequest) (*AuthResponse, error)
	// Login authenticates a user and returns a JWT token
	Login(context.Context, *LoginRequest) (*AuthResponse, error)
	// ValidateToken verifies a JWT and returns the user ID if valid
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	// GetGoogleAuthURL retrieves the Google authentication URL
	GetGoogleAuthURL(context.Context, *GetGoogleAuthURLRequest) (*GetGoogleAuthURLResponse, error)
	// HandleGoogleCallback handles the callback from Google authentication
	HandleGoogleCallback(context.Context, *HandleGoogleCallbackRequest) (*AuthResponse, error)
	// GitHub OAuth flow – step 1: get install URL
	GetGitHubAuthURL(context.Context, *GetGitHubAuthURLRequest) (*GetGitHubAuthURLResponse, error)
	// GitHub OAuth flow – step 2: handle callback with installation_id
	HandleGitHubCallback(context.Context, *HandleGitHubCallbackRequest) (*AuthResponse, error)
	// Internal – runner-allocator asks for 1-hour access token
	GetGitHubAccessToken(context.Context, *GetGitHubAccessTokenRequest) (*GetGitHubAccessTokenResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) Signup(context.Context, *SignupRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (UnimplementedAuthServiceServer) Login(context.Context, *LoginRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthServiceServer) ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedAuthServiceServer) GetGoogleAuthURL(context.Context, *GetGoogleAuthURLRequest) (*GetGoogleAuthURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoogleAuthURL not implemented")
}
func (UnimplementedAuthServiceServer) HandleGoogleCallback(context.Context, *HandleGoogleCallbackRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleGoogleCallback not implemented")
}
func (UnimplementedAuthServiceServer) GetGitHubAuthURL(context.Context, *GetGitHubAuthURLRequest) (*GetGitHubAuthURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGitHubAuthURL not implemented")
}
func (UnimplementedAuthServiceServer) HandleGitHubCallback(context.Context, *HandleGitHubCallbackRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleGitHubCallback not implemented")
}
func (UnimplementedAuthServiceServer) GetGitHubAccessToken(context.Context, *GetGitHubAccessTokenRequest) (*GetGitHubAccessTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGitHubAccessToken not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Signup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Signup(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ValidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetGoogleAuthURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoogleAuthURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetGoogleAuthURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetGoogleAuthURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetGoogleAuthURL(ctx, req.(*GetGoogleAuthURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_HandleGoogleCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleGoogleCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).HandleGoogleCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_HandleGoogleCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).HandleGoogleCallback(ctx, req.(*HandleGoogleCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetGitHubAuthURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGitHubAuthURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetGitHubAuthURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetGitHubAuthURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetGitHubAuthURL(ctx, req.(*GetGitHubAuthURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_HandleGitHubCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleGitHubCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).HandleGitHubCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_HandleGitHubCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).HandleGitHubCallback(ctx, req.(*HandleGitHubCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetGitHubAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGitHubAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetGitHubAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetGitHubAccessToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetGitHubAccessToken(ctx, req.(*GetGitHubAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signup",
			Handler:    _AuthService_Signup_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _AuthService_ValidateToken_Handler,
		},
		{
			MethodName: "GetGoogleAuthURL",
			Handler:    _AuthService_GetGoogleAuthURL_Handler,
		},
		{
			MethodName: "HandleGoogleCallback",
			Handler:    _AuthService_HandleGoogleCallback_Handler,
		},
		{
			MethodName: "GetGitHubAuthURL",
			Handler:    _AuthService_GetGitHubAuthURL_Handler,
		},
		{
			MethodName: "HandleGitHubCallback",
			Handler:    _AuthService_HandleGitHubCallback_Handler,
		},
		{
			MethodName: "GetGitHubAccessToken",
			Handler:    _AuthService_GetGitHubAccessToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
