// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/project.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectStatus int32

const (
	ProjectStatus_PROJECT_STATUS_UNSPECIFIED ProjectStatus = 0
	ProjectStatus_STOPPED                    ProjectStatus = 1
	ProjectStatus_STARTING                   ProjectStatus = 2
	ProjectStatus_RUNNING                    ProjectStatus = 3
	ProjectStatus_ERROR                      ProjectStatus = 4
)

// Enum value maps for ProjectStatus.
var (
	ProjectStatus_name = map[int32]string{
		0: "PROJECT_STATUS_UNSPECIFIED",
		1: "STOPPED",
		2: "STARTING",
		3: "RUNNING",
		4: "ERROR",
	}
	ProjectStatus_value = map[string]int32{
		"PROJECT_STATUS_UNSPECIFIED": 0,
		"STOPPED":                    1,
		"STARTING":                   2,
		"RUNNING":                    3,
		"ERROR":                      4,
	}
)

func (x ProjectStatus) Enum() *ProjectStatus {
	p := new(ProjectStatus)
	*p = x
	return p
}

func (x ProjectStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_project_proto_enumTypes[0].Descriptor()
}

func (ProjectStatus) Type() protoreflect.EnumType {
	return &file_proto_project_proto_enumTypes[0]
}

func (x ProjectStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectStatus.Descriptor instead.
func (ProjectStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{0}
}

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RepoUrl       string                 `protobuf:"bytes,3,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_proto_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProjectRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProjectRequest) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

type CreateProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectResponse) Reset() {
	*x = CreateProjectResponse{}
	mi := &file_proto_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectResponse) ProtoMessage() {}

func (x *CreateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectResponse.ProtoReflect.Descriptor instead.
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProjectResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type StartWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"` // UUID
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkspaceRequest) Reset() {
	*x = StartWorkspaceRequest{}
	mi := &file_proto_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkspaceRequest) ProtoMessage() {}

func (x *StartWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*StartWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{2}
}

func (x *StartWorkspaceRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *StartWorkspaceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type StartWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Status        ProjectStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=project.ProjectStatus" json:"status,omitempty"`
	AtlasId       string                 `protobuf:"bytes,3,opt,name=atlas_id,json=atlasId,proto3" json:"atlas_id,omitempty"` // "ws-{uuid}"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkspaceResponse) Reset() {
	*x = StartWorkspaceResponse{}
	mi := &file_proto_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkspaceResponse) ProtoMessage() {}

func (x *StartWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*StartWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{3}
}

func (x *StartWorkspaceResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StartWorkspaceResponse) GetStatus() ProjectStatus {
	if x != nil {
		return x.Status
	}
	return ProjectStatus_PROJECT_STATUS_UNSPECIFIED
}

func (x *StartWorkspaceResponse) GetAtlasId() string {
	if x != nil {
		return x.AtlasId
	}
	return ""
}

type StopWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	AtlasId       string                 `protobuf:"bytes,2,opt,name=atlas_id,json=atlasId,proto3" json:"atlas_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopWorkspaceRequest) Reset() {
	*x = StopWorkspaceRequest{}
	mi := &file_proto_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopWorkspaceRequest) ProtoMessage() {}

func (x *StopWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*StopWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{4}
}

func (x *StopWorkspaceRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *StopWorkspaceRequest) GetAtlasId() string {
	if x != nil {
		return x.AtlasId
	}
	return ""
}

type StopWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopWorkspaceResponse) Reset() {
	*x = StopWorkspaceResponse{}
	mi := &file_proto_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopWorkspaceResponse) ProtoMessage() {}

func (x *StopWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*StopWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{5}
}

func (x *StopWorkspaceResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type WebhookUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AtlasId       string                 `protobuf:"bytes,1,opt,name=atlas_id,json=atlasId,proto3" json:"atlas_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                    // READY | ERROR
	CallbackToken string                 `protobuf:"bytes,3,opt,name=callback_token,json=callbackToken,proto3" json:"callback_token,omitempty"` // webhook_secret from StartWorkspace
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookUpdateRequest) Reset() {
	*x = WebhookUpdateRequest{}
	mi := &file_proto_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookUpdateRequest) ProtoMessage() {}

func (x *WebhookUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookUpdateRequest.ProtoReflect.Descriptor instead.
func (*WebhookUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{6}
}

func (x *WebhookUpdateRequest) GetAtlasId() string {
	if x != nil {
		return x.AtlasId
	}
	return ""
}

func (x *WebhookUpdateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WebhookUpdateRequest) GetCallbackToken() string {
	if x != nil {
		return x.CallbackToken
	}
	return ""
}

type WebhookUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookUpdateResponse) Reset() {
	*x = WebhookUpdateResponse{}
	mi := &file_proto_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookUpdateResponse) ProtoMessage() {}

func (x *WebhookUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookUpdateResponse.ProtoReflect.Descriptor instead.
func (*WebhookUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{7}
}

func (x *WebhookUpdateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type VerifyAndCompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AtlasId       string                 `protobuf:"bytes,1,opt,name=atlas_id,json=atlasId,proto3" json:"atlas_id,omitempty"`
	CallbackToken string                 `protobuf:"bytes,2,opt,name=callback_token,json=callbackToken,proto3" json:"callback_token,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // READY | ERROR
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAndCompleteRequest) Reset() {
	*x = VerifyAndCompleteRequest{}
	mi := &file_proto_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAndCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAndCompleteRequest) ProtoMessage() {}

func (x *VerifyAndCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAndCompleteRequest.ProtoReflect.Descriptor instead.
func (*VerifyAndCompleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyAndCompleteRequest) GetAtlasId() string {
	if x != nil {
		return x.AtlasId
	}
	return ""
}

func (x *VerifyAndCompleteRequest) GetCallbackToken() string {
	if x != nil {
		return x.CallbackToken
	}
	return ""
}

func (x *VerifyAndCompleteRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type VerifyAndCompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Status        ProjectStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=project.ProjectStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAndCompleteResponse) Reset() {
	*x = VerifyAndCompleteResponse{}
	mi := &file_proto_project_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAndCompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAndCompleteResponse) ProtoMessage() {}

func (x *VerifyAndCompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAndCompleteResponse.ProtoReflect.Descriptor instead.
func (*VerifyAndCompleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyAndCompleteResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *VerifyAndCompleteResponse) GetStatus() ProjectStatus {
	if x != nil {
		return x.Status
	}
	return ProjectStatus_PROJECT_STATUS_UNSPECIFIED
}

type IsOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"` // atlas_id ("ws-{uuid}")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsOwnerRequest) Reset() {
	*x = IsOwnerRequest{}
	mi := &file_proto_project_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsOwnerRequest) ProtoMessage() {}

func (x *IsOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsOwnerRequest.ProtoReflect.Descriptor instead.
func (*IsOwnerRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{10}
}

func (x *IsOwnerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IsOwnerRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type IsOwnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOwner       bool                   `protobuf:"varint,1,opt,name=is_owner,json=isOwner,proto3" json:"is_owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsOwnerResponse) Reset() {
	*x = IsOwnerResponse{}
	mi := &file_proto_project_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsOwnerResponse) ProtoMessage() {}

func (x *IsOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsOwnerResponse.ProtoReflect.Descriptor instead.
func (*IsOwnerResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{11}
}

func (x *IsOwnerResponse) GetIsOwner() bool {
	if x != nil {
		return x.IsOwner
	}
	return false
}

var File_proto_project_proto protoreflect.FileDescriptor

const file_proto_project_proto_rawDesc = "" +
	"\n" +
	"\x13proto/project.proto\x12\aproject\"^\n" +
	"\x14CreateProjectRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\brepo_url\x18\x03 \x01(\tR\arepoUrl\"6\n" +
	"\x15CreateProjectResponse\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"O\n" +
	"\x15StartWorkspaceRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"s\n" +
	"\x16StartWorkspaceResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.project.ProjectStatusR\x06status\x12\x19\n" +
	"\batlas_id\x18\x03 \x01(\tR\aatlasId\"P\n" +
	"\x14StopWorkspaceRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x19\n" +
	"\batlas_id\x18\x02 \x01(\tR\aatlasId\"'\n" +
	"\x15StopWorkspaceResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"p\n" +
	"\x14WebhookUpdateRequest\x12\x19\n" +
	"\batlas_id\x18\x01 \x01(\tR\aatlasId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0ecallback_token\x18\x03 \x01(\tR\rcallbackToken\"'\n" +
	"\x15WebhookUpdateResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"t\n" +
	"\x18VerifyAndCompleteRequest\x12\x19\n" +
	"\batlas_id\x18\x01 \x01(\tR\aatlasId\x12%\n" +
	"\x0ecallback_token\x18\x02 \x01(\tR\rcallbackToken\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"[\n" +
	"\x19VerifyAndCompleteResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.project.ProjectStatusR\x06status\"H\n" +
	"\x0eIsOwnerRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\",\n" +
	"\x0fIsOwnerResponse\x12\x19\n" +
	"\bis_owner\x18\x01 \x01(\bR\aisOwner*b\n" +
	"\rProjectStatus\x12\x1e\n" +
	"\x1aPROJECT_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aSTOPPED\x10\x01\x12\f\n" +
	"\bSTARTING\x10\x02\x12\v\n" +
	"\aRUNNING\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x042\xed\x03\n" +
	"\x0eProjectService\x12N\n" +
	"\rCreateProject\x12\x1d.project.CreateProjectRequest\x1a\x1e.project.CreateProjectResponse\x12Q\n" +
	"\x0eStartWorkspace\x12\x1e.project.StartWorkspaceRequest\x1a\x1f.project.StartWorkspaceResponse\x12N\n" +
	"\rStopWorkspace\x12\x1d.project.StopWorkspaceRequest\x1a\x1e.project.StopWorkspaceResponse\x12N\n" +
	"\rWebhookUpdate\x12\x1d.project.WebhookUpdateRequest\x1a\x1e.project.WebhookUpdateResponse\x12Z\n" +
	"\x11VerifyAndComplete\x12!.project.VerifyAndCompleteRequest\x1a\".project.VerifyAndCompleteResponse\x12<\n" +
	"\aIsOwner\x12\x17.project.IsOwnerRequest\x1a\x18.project.IsOwnerResponseB-Z+github.com/Aadithya-J/code_nest/proto;protob\x06proto3"

var (
	file_proto_project_proto_rawDescOnce sync.Once
	file_proto_project_proto_rawDescData []byte
)

func file_proto_project_proto_rawDescGZIP() []byte {
	file_proto_project_proto_rawDescOnce.Do(func() {
		file_proto_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_project_proto_rawDesc), len(file_proto_project_proto_rawDesc)))
	})
	return file_proto_project_proto_rawDescData
}

var file_proto_project_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_project_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_project_proto_goTypes = []any{
	(ProjectStatus)(0),                // 0: project.ProjectStatus
	(*CreateProjectRequest)(nil),      // 1: project.CreateProjectRequest
	(*CreateProjectResponse)(nil),     // 2: project.CreateProjectResponse
	(*StartWorkspaceRequest)(nil),     // 3: project.StartWorkspaceRequest
	(*StartWorkspaceResponse)(nil),    // 4: project.StartWorkspaceResponse
	(*StopWorkspaceRequest)(nil),      // 5: project.StopWorkspaceRequest
	(*StopWorkspaceResponse)(nil),     // 6: project.StopWorkspaceResponse
	(*WebhookUpdateRequest)(nil),      // 7: project.WebhookUpdateRequest
	(*WebhookUpdateResponse)(nil),     // 8: project.WebhookUpdateResponse
	(*VerifyAndCompleteRequest)(nil),  // 9: project.VerifyAndCompleteRequest
	(*VerifyAndCompleteResponse)(nil), // 10: project.VerifyAndCompleteResponse
	(*IsOwnerRequest)(nil),            // 11: project.IsOwnerRequest
	(*IsOwnerResponse)(nil),           // 12: project.IsOwnerResponse
}
var file_proto_project_proto_depIdxs = []int32{
	0,  // 0: project.StartWorkspaceResponse.status:type_name -> project.ProjectStatus
	0,  // 1: project.VerifyAndCompleteResponse.status:type_name -> project.ProjectStatus
	1,  // 2: project.ProjectService.CreateProject:input_type -> project.CreateProjectRequest
	3,  // 3: project.ProjectService.StartWorkspace:input_type -> project.StartWorkspaceRequest
	5,  // 4: project.ProjectService.StopWorkspace:input_type -> project.StopWorkspaceRequest
	7,  // 5: project.ProjectService.WebhookUpdate:input_type -> project.WebhookUpdateRequest
	9,  // 6: project.ProjectService.VerifyAndComplete:input_type -> project.VerifyAndCompleteRequest
	11, // 7: project.ProjectService.IsOwner:input_type -> project.IsOwnerRequest
	2,  // 8: project.ProjectService.CreateProject:output_type -> project.CreateProjectResponse
	4,  // 9: project.ProjectService.StartWorkspace:output_type -> project.StartWorkspaceResponse
	6,  // 10: project.ProjectService.StopWorkspace:output_type -> project.StopWorkspaceResponse
	8,  // 11: project.ProjectService.WebhookUpdate:output_type -> project.WebhookUpdateResponse
	10, // 12: project.ProjectService.VerifyAndComplete:output_type -> project.VerifyAndCompleteResponse
	12, // 13: project.ProjectService.IsOwner:output_type -> project.IsOwnerResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_project_proto_init() }
func file_proto_project_proto_init() {
	if File_proto_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_project_proto_rawDesc), len(file_proto_project_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_project_proto_goTypes,
		DependencyIndexes: file_proto_project_proto_depIdxs,
		EnumInfos:         file_proto_project_proto_enumTypes,
		MessageInfos:      file_proto_project_proto_msgTypes,
	}.Build()
	File_proto_project_proto = out.File
	file_proto_project_proto_goTypes = nil
	file_proto_project_proto_depIdxs = nil
}
