// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: workspace.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a single project.
type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_workspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Project) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Project) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"` // Injected by API Gateway after auth.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_workspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProjectRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"` // Injected by API Gateway after auth.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectsRequest) Reset() {
	*x = GetProjectsRequest{}
	mi := &file_workspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectsRequest) ProtoMessage() {}

func (x *GetProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectsRequest.ProtoReflect.Descriptor instead.
func (*GetProjectsRequest) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{2}
}

func (x *GetProjectsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectsResponse) Reset() {
	*x = GetProjectsResponse{}
	mi := &file_workspace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectsResponse) ProtoMessage() {}

func (x *GetProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectsResponse.ProtoReflect.Descriptor instead.
func (*GetProjectsResponse) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{3}
}

func (x *GetProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type UpdateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ID of the project to update.
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"` // Injected by API Gateway for authorization check.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectRequest) Reset() {
	*x = UpdateProjectRequest{}
	mi := &file_workspace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectRequest) ProtoMessage() {}

func (x *UpdateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProjectRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`         // ID of the project to delete.
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"` // Injected by API Gateway for authorization check.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectRequest) Reset() {
	*x = DeleteProjectRequest{}
	mi := &file_workspace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectRequest) ProtoMessage() {}

func (x *DeleteProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteProjectRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectResponse) Reset() {
	*x = DeleteProjectResponse{}
	mi := &file_workspace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectResponse) ProtoMessage() {}

func (x *DeleteProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteProjectResponse) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteProjectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteProjectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// A standard response that returns a single project.
type ProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectResponse) Reset() {
	*x = ProjectResponse{}
	mi := &file_workspace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectResponse) ProtoMessage() {}

func (x *ProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectResponse.ProtoReflect.Descriptor instead.
func (*ProjectResponse) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{7}
}

func (x *ProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

// Represents a single file in a project.
type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=projectId,proto3" json:"projectId,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_workspace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{8}
}

func (x *File) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *File) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *File) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type SaveFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"` // For auth check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveFileRequest) Reset() {
	*x = SaveFileRequest{}
	mi := &file_workspace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveFileRequest) ProtoMessage() {}

func (x *SaveFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveFileRequest.ProtoReflect.Descriptor instead.
func (*SaveFileRequest) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{9}
}

func (x *SaveFileRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SaveFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SaveFileRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SaveFileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"` // For auth check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_workspace_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{10}
}

func (x *GetFileRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetFileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"` // For auth check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_workspace_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{11}
}

func (x *ListFilesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListFilesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*File                `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_workspace_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{12}
}

func (x *ListFilesResponse) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

type FileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *File                  `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	mi := &file_workspace_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{13}
}

func (x *FileResponse) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"` // For auth check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_workspace_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteFileRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeleteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeleteFileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_workspace_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RenameFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	OldPath       string                 `protobuf:"bytes,2,opt,name=oldPath,proto3" json:"oldPath,omitempty"`
	NewPath       string                 `protobuf:"bytes,3,opt,name=newPath,proto3" json:"newPath,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"` // For auth check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameFileRequest) Reset() {
	*x = RenameFileRequest{}
	mi := &file_workspace_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameFileRequest) ProtoMessage() {}

func (x *RenameFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameFileRequest.ProtoReflect.Descriptor instead.
func (*RenameFileRequest) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{16}
}

func (x *RenameFileRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *RenameFileRequest) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *RenameFileRequest) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

func (x *RenameFileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetFileTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"` // For auth check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileTreeRequest) Reset() {
	*x = GetFileTreeRequest{}
	mi := &file_workspace_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileTreeRequest) ProtoMessage() {}

func (x *GetFileTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileTreeRequest.ProtoReflect.Descriptor instead.
func (*GetFileTreeRequest) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{17}
}

func (x *GetFileTreeRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetFileTreeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FileTreeNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	IsDirectory   bool                   `protobuf:"varint,3,opt,name=isDirectory,proto3" json:"isDirectory,omitempty"`
	Children      []*FileTreeNode        `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTreeNode) Reset() {
	*x = FileTreeNode{}
	mi := &file_workspace_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTreeNode) ProtoMessage() {}

func (x *FileTreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTreeNode.ProtoReflect.Descriptor instead.
func (*FileTreeNode) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{18}
}

func (x *FileTreeNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileTreeNode) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileTreeNode) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

func (x *FileTreeNode) GetChildren() []*FileTreeNode {
	if x != nil {
		return x.Children
	}
	return nil
}

type GetFileTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*FileTreeNode        `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileTreeResponse) Reset() {
	*x = GetFileTreeResponse{}
	mi := &file_workspace_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileTreeResponse) ProtoMessage() {}

func (x *GetFileTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileTreeResponse.ProtoReflect.Descriptor instead.
func (*GetFileTreeResponse) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{19}
}

func (x *GetFileTreeResponse) GetNodes() []*FileTreeNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type CreateWorkspaceSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`         // Injected by API Gateway
	GitRepoUrl    string                 `protobuf:"bytes,3,opt,name=gitRepoUrl,proto3" json:"gitRepoUrl,omitempty"` // Optional: URL of the git repo to clone
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkspaceSessionRequest) Reset() {
	*x = CreateWorkspaceSessionRequest{}
	mi := &file_workspace_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkspaceSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkspaceSessionRequest) ProtoMessage() {}

func (x *CreateWorkspaceSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkspaceSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkspaceSessionRequest) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{20}
}

func (x *CreateWorkspaceSessionRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateWorkspaceSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateWorkspaceSessionRequest) GetGitRepoUrl() string {
	if x != nil {
		return x.GitRepoUrl
	}
	return ""
}

type ReleaseWorkspaceSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=projectId,proto3" json:"projectId,omitempty"` // For authorization and context
	UserId        string                 `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`       // For authorization
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseWorkspaceSessionRequest) Reset() {
	*x = ReleaseWorkspaceSessionRequest{}
	mi := &file_workspace_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseWorkspaceSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseWorkspaceSessionRequest) ProtoMessage() {}

func (x *ReleaseWorkspaceSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseWorkspaceSessionRequest.ProtoReflect.Descriptor instead.
func (*ReleaseWorkspaceSessionRequest) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{21}
}

func (x *ReleaseWorkspaceSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReleaseWorkspaceSessionRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ReleaseWorkspaceSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type WorkspaceSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceSessionResponse) Reset() {
	*x = WorkspaceSessionResponse{}
	mi := &file_workspace_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceSessionResponse) ProtoMessage() {}

func (x *WorkspaceSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceSessionResponse.ProtoReflect.Descriptor instead.
func (*WorkspaceSessionResponse) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{22}
}

func (x *WorkspaceSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WorkspaceSessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkspaceSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAllActiveSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllActiveSessionsRequest) Reset() {
	*x = GetAllActiveSessionsRequest{}
	mi := &file_workspace_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllActiveSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllActiveSessionsRequest) ProtoMessage() {}

func (x *GetAllActiveSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllActiveSessionsRequest.ProtoReflect.Descriptor instead.
func (*GetAllActiveSessionsRequest) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{23}
}

type ActiveSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=projectId,proto3" json:"projectId,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveSession) Reset() {
	*x = ActiveSession{}
	mi := &file_workspace_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveSession) ProtoMessage() {}

func (x *ActiveSession) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveSession.ProtoReflect.Descriptor instead.
func (*ActiveSession) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{24}
}

func (x *ActiveSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ActiveSession) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ActiveSession) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ActiveSession) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetAllActiveSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*ActiveSession       `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllActiveSessionsResponse) Reset() {
	*x = GetAllActiveSessionsResponse{}
	mi := &file_workspace_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllActiveSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllActiveSessionsResponse) ProtoMessage() {}

func (x *GetAllActiveSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllActiveSessionsResponse.ProtoReflect.Descriptor instead.
func (*GetAllActiveSessionsResponse) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{25}
}

func (x *GetAllActiveSessionsResponse) GetSessions() []*ActiveSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

var File_workspace_proto protoreflect.FileDescriptor

const file_workspace_proto_rawDesc = "" +
	"\n" +
	"\x0fworkspace.proto\x12\x05proto\"\xa3\x01\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06userId\x18\x04 \x01(\tR\x06userId\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x06 \x01(\tR\tupdatedAt\"d\n" +
	"\x14CreateProjectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\tR\x06userId\",\n" +
	"\x12GetProjectsRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"A\n" +
	"\x13GetProjectsResponse\x12*\n" +
	"\bprojects\x18\x01 \x03(\v2\x0e.proto.ProjectR\bprojects\"t\n" +
	"\x14UpdateProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06userId\x18\x04 \x01(\tR\x06userId\">\n" +
	"\x14DeleteProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\"K\n" +
	"\x15DeleteProjectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\";\n" +
	"\x0fProjectResponse\x12(\n" +
	"\aproject\x18\x01 \x01(\v2\x0e.proto.ProjectR\aproject\"\x80\x01\n" +
	"\x04File\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tprojectId\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1c\n" +
	"\tupdatedAt\x18\x05 \x01(\tR\tupdatedAt\"u\n" +
	"\x0fSaveFileRequest\x12\x1c\n" +
	"\tprojectId\x18\x01 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06userId\x18\x04 \x01(\tR\x06userId\"Z\n" +
	"\x0eGetFileRequest\x12\x1c\n" +
	"\tprojectId\x18\x01 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\tR\x06userId\"H\n" +
	"\x10ListFilesRequest\x12\x1c\n" +
	"\tprojectId\x18\x01 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\"6\n" +
	"\x11ListFilesResponse\x12!\n" +
	"\x05files\x18\x01 \x03(\v2\v.proto.FileR\x05files\"/\n" +
	"\fFileResponse\x12\x1f\n" +
	"\x04file\x18\x01 \x01(\v2\v.proto.FileR\x04file\"]\n" +
	"\x11DeleteFileRequest\x12\x1c\n" +
	"\tprojectId\x18\x01 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\tR\x06userId\"H\n" +
	"\x12DeleteFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"}\n" +
	"\x11RenameFileRequest\x12\x1c\n" +
	"\tprojectId\x18\x01 \x01(\tR\tprojectId\x12\x18\n" +
	"\aoldPath\x18\x02 \x01(\tR\aoldPath\x12\x18\n" +
	"\anewPath\x18\x03 \x01(\tR\anewPath\x12\x16\n" +
	"\x06userId\x18\x04 \x01(\tR\x06userId\"J\n" +
	"\x12GetFileTreeRequest\x12\x1c\n" +
	"\tprojectId\x18\x01 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\"\x89\x01\n" +
	"\fFileTreeNode\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12 \n" +
	"\visDirectory\x18\x03 \x01(\bR\visDirectory\x12/\n" +
	"\bchildren\x18\x04 \x03(\v2\x13.proto.FileTreeNodeR\bchildren\"@\n" +
	"\x13GetFileTreeResponse\x12)\n" +
	"\x05nodes\x18\x01 \x03(\v2\x13.proto.FileTreeNodeR\x05nodes\"u\n" +
	"\x1dCreateWorkspaceSessionRequest\x12\x1c\n" +
	"\tprojectId\x18\x01 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"gitRepoUrl\x18\x03 \x01(\tR\n" +
	"gitRepoUrl\"t\n" +
	"\x1eReleaseWorkspaceSessionRequest\x12\x1c\n" +
	"\tsessionId\x18\x01 \x01(\tR\tsessionId\x12\x1c\n" +
	"\tprojectId\x18\x02 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\tR\x06userId\"j\n" +
	"\x18WorkspaceSessionResponse\x12\x1c\n" +
	"\tsessionId\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x1d\n" +
	"\x1bGetAllActiveSessionsRequest\"{\n" +
	"\rActiveSession\x12\x1c\n" +
	"\tsessionId\x18\x01 \x01(\tR\tsessionId\x12\x1c\n" +
	"\tprojectId\x18\x02 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"P\n" +
	"\x1cGetAllActiveSessionsResponse\x120\n" +
	"\bsessions\x18\x01 \x03(\v2\x14.proto.ActiveSessionR\bsessions2\xa6\x05\n" +
	"\x10WorkspaceService\x12D\n" +
	"\rCreateProject\x12\x1b.proto.CreateProjectRequest\x1a\x16.proto.ProjectResponse\x12D\n" +
	"\vGetProjects\x12\x19.proto.GetProjectsRequest\x1a\x1a.proto.GetProjectsResponse\x12D\n" +
	"\rUpdateProject\x12\x1b.proto.UpdateProjectRequest\x1a\x16.proto.ProjectResponse\x12J\n" +
	"\rDeleteProject\x12\x1b.proto.DeleteProjectRequest\x1a\x1c.proto.DeleteProjectResponse\x127\n" +
	"\bSaveFile\x12\x16.proto.SaveFileRequest\x1a\x13.proto.FileResponse\x125\n" +
	"\aGetFile\x12\x15.proto.GetFileRequest\x1a\x13.proto.FileResponse\x12>\n" +
	"\tListFiles\x12\x17.proto.ListFilesRequest\x1a\x18.proto.ListFilesResponse\x12A\n" +
	"\n" +
	"DeleteFile\x12\x18.proto.DeleteFileRequest\x1a\x19.proto.DeleteFileResponse\x12;\n" +
	"\n" +
	"RenameFile\x12\x18.proto.RenameFileRequest\x1a\x13.proto.FileResponse\x12D\n" +
	"\vGetFileTree\x12\x19.proto.GetFileTreeRequest\x1a\x1a.proto.GetFileTreeResponse2\xb5\x02\n" +
	"\x0eSessionService\x12_\n" +
	"\x16CreateWorkspaceSession\x12$.proto.CreateWorkspaceSessionRequest\x1a\x1f.proto.WorkspaceSessionResponse\x12a\n" +
	"\x17ReleaseWorkspaceSession\x12%.proto.ReleaseWorkspaceSessionRequest\x1a\x1f.proto.WorkspaceSessionResponse\x12_\n" +
	"\x14GetAllActiveSessions\x12\".proto.GetAllActiveSessionsRequest\x1a#.proto.GetAllActiveSessionsResponseB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_workspace_proto_rawDescOnce sync.Once
	file_workspace_proto_rawDescData []byte
)

func file_workspace_proto_rawDescGZIP() []byte {
	file_workspace_proto_rawDescOnce.Do(func() {
		file_workspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workspace_proto_rawDesc), len(file_workspace_proto_rawDesc)))
	})
	return file_workspace_proto_rawDescData
}

var file_workspace_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_workspace_proto_goTypes = []any{
	(*Project)(nil),                        // 0: proto.Project
	(*CreateProjectRequest)(nil),           // 1: proto.CreateProjectRequest
	(*GetProjectsRequest)(nil),             // 2: proto.GetProjectsRequest
	(*GetProjectsResponse)(nil),            // 3: proto.GetProjectsResponse
	(*UpdateProjectRequest)(nil),           // 4: proto.UpdateProjectRequest
	(*DeleteProjectRequest)(nil),           // 5: proto.DeleteProjectRequest
	(*DeleteProjectResponse)(nil),          // 6: proto.DeleteProjectResponse
	(*ProjectResponse)(nil),                // 7: proto.ProjectResponse
	(*File)(nil),                           // 8: proto.File
	(*SaveFileRequest)(nil),                // 9: proto.SaveFileRequest
	(*GetFileRequest)(nil),                 // 10: proto.GetFileRequest
	(*ListFilesRequest)(nil),               // 11: proto.ListFilesRequest
	(*ListFilesResponse)(nil),              // 12: proto.ListFilesResponse
	(*FileResponse)(nil),                   // 13: proto.FileResponse
	(*DeleteFileRequest)(nil),              // 14: proto.DeleteFileRequest
	(*DeleteFileResponse)(nil),             // 15: proto.DeleteFileResponse
	(*RenameFileRequest)(nil),              // 16: proto.RenameFileRequest
	(*GetFileTreeRequest)(nil),             // 17: proto.GetFileTreeRequest
	(*FileTreeNode)(nil),                   // 18: proto.FileTreeNode
	(*GetFileTreeResponse)(nil),            // 19: proto.GetFileTreeResponse
	(*CreateWorkspaceSessionRequest)(nil),  // 20: proto.CreateWorkspaceSessionRequest
	(*ReleaseWorkspaceSessionRequest)(nil), // 21: proto.ReleaseWorkspaceSessionRequest
	(*WorkspaceSessionResponse)(nil),       // 22: proto.WorkspaceSessionResponse
	(*GetAllActiveSessionsRequest)(nil),    // 23: proto.GetAllActiveSessionsRequest
	(*ActiveSession)(nil),                  // 24: proto.ActiveSession
	(*GetAllActiveSessionsResponse)(nil),   // 25: proto.GetAllActiveSessionsResponse
}
var file_workspace_proto_depIdxs = []int32{
	0,  // 0: proto.GetProjectsResponse.projects:type_name -> proto.Project
	0,  // 1: proto.ProjectResponse.project:type_name -> proto.Project
	8,  // 2: proto.ListFilesResponse.files:type_name -> proto.File
	8,  // 3: proto.FileResponse.file:type_name -> proto.File
	18, // 4: proto.FileTreeNode.children:type_name -> proto.FileTreeNode
	18, // 5: proto.GetFileTreeResponse.nodes:type_name -> proto.FileTreeNode
	24, // 6: proto.GetAllActiveSessionsResponse.sessions:type_name -> proto.ActiveSession
	1,  // 7: proto.WorkspaceService.CreateProject:input_type -> proto.CreateProjectRequest
	2,  // 8: proto.WorkspaceService.GetProjects:input_type -> proto.GetProjectsRequest
	4,  // 9: proto.WorkspaceService.UpdateProject:input_type -> proto.UpdateProjectRequest
	5,  // 10: proto.WorkspaceService.DeleteProject:input_type -> proto.DeleteProjectRequest
	9,  // 11: proto.WorkspaceService.SaveFile:input_type -> proto.SaveFileRequest
	10, // 12: proto.WorkspaceService.GetFile:input_type -> proto.GetFileRequest
	11, // 13: proto.WorkspaceService.ListFiles:input_type -> proto.ListFilesRequest
	14, // 14: proto.WorkspaceService.DeleteFile:input_type -> proto.DeleteFileRequest
	16, // 15: proto.WorkspaceService.RenameFile:input_type -> proto.RenameFileRequest
	17, // 16: proto.WorkspaceService.GetFileTree:input_type -> proto.GetFileTreeRequest
	20, // 17: proto.SessionService.CreateWorkspaceSession:input_type -> proto.CreateWorkspaceSessionRequest
	21, // 18: proto.SessionService.ReleaseWorkspaceSession:input_type -> proto.ReleaseWorkspaceSessionRequest
	23, // 19: proto.SessionService.GetAllActiveSessions:input_type -> proto.GetAllActiveSessionsRequest
	7,  // 20: proto.WorkspaceService.CreateProject:output_type -> proto.ProjectResponse
	3,  // 21: proto.WorkspaceService.GetProjects:output_type -> proto.GetProjectsResponse
	7,  // 22: proto.WorkspaceService.UpdateProject:output_type -> proto.ProjectResponse
	6,  // 23: proto.WorkspaceService.DeleteProject:output_type -> proto.DeleteProjectResponse
	13, // 24: proto.WorkspaceService.SaveFile:output_type -> proto.FileResponse
	13, // 25: proto.WorkspaceService.GetFile:output_type -> proto.FileResponse
	12, // 26: proto.WorkspaceService.ListFiles:output_type -> proto.ListFilesResponse
	15, // 27: proto.WorkspaceService.DeleteFile:output_type -> proto.DeleteFileResponse
	13, // 28: proto.WorkspaceService.RenameFile:output_type -> proto.FileResponse
	19, // 29: proto.WorkspaceService.GetFileTree:output_type -> proto.GetFileTreeResponse
	22, // 30: proto.SessionService.CreateWorkspaceSession:output_type -> proto.WorkspaceSessionResponse
	22, // 31: proto.SessionService.ReleaseWorkspaceSession:output_type -> proto.WorkspaceSessionResponse
	25, // 32: proto.SessionService.GetAllActiveSessions:output_type -> proto.GetAllActiveSessionsResponse
	20, // [20:33] is the sub-list for method output_type
	7,  // [7:20] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_workspace_proto_init() }
func file_workspace_proto_init() {
	if File_workspace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workspace_proto_rawDesc), len(file_workspace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_workspace_proto_goTypes,
		DependencyIndexes: file_workspace_proto_depIdxs,
		MessageInfos:      file_workspace_proto_msgTypes,
	}.Build()
	File_workspace_proto = out.File
	file_workspace_proto_goTypes = nil
	file_workspace_proto_depIdxs = nil
}
