services:
  kafka:
    image: confluentinc/cp-kafka:latest
    platform: linux/arm64
    container_name: kafka
    ports:
      - "9092:9092"      # containers
      - "19092:19092"    # host apps
    environment:
      # ---- KRaft essentials ----
      CLUSTER_ID: "tUwsCPfnQIWymV9iTWpcrw"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      # ---- listeners ----
      KAFKA_LISTENERS: >
        PLAINTEXT://0.0.0.0:9092,
        HOST://0.0.0.0:19092,
        CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://kafka:9092,
        HOST://localhost:19092,
        CONTROLLER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        PLAINTEXT:PLAINTEXT,
        HOST:PLAINTEXT,
        CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # ---- single-node tweaks ----
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

  init-kafka:
    image: confluentinc/cp-kafka:latest
    platform: linux/arm64
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: /bin/sh
    command:
      - -c
      - |
        echo "Waiting for Kafka to be ready..."
        until kafka-topics --bootstrap-server kafka:9092 --list; do
          echo "Kafka not ready, sleeping..."
          sleep 2
        done
        echo "Kafka is ready!"

        echo "Creating Kafka topics..."
        kafka-topics --bootstrap-server kafka:9092 --create \
          --if-not-exists --topic workspace-topic \
          --partitions 1 --replication-factor 1

        echo "Successfully created topics:"
        kafka-topics --bootstrap-server kafka:9092 --list

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
